name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git plugins
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install MkDocs and plugins
      run: |
        pip install \
          mkdocs \
          mkdocs-material \
          mkdocs-minify-plugin \
          mkdocs-git-revision-date-localized-plugin \
          mkdocs-git-committers-plugin-2 \
          mkdocs-social-plugin \
          mkdocs-tags-plugin \
          mkdocs-glightbox \
          pillow \
          cairosvg
    
    - name: Install Lua
      run: sudo apt-get update && sudo apt-get install -y lua5.3
    
    - name: Validate MkDocs configuration
      run: |
        echo "Validating MkDocs configuration..."
        mkdocs build --strict
        
        echo "MkDocs configuration validation passed"
    
    - name: Install StyLua for code formatting
      run: |
        curl -L https://github.com/JohnnyMorganz/StyLua/releases/download/v2.1.0/stylua-linux-x86_64.zip -o stylua.zip
        unzip stylua.zip
        chmod +x stylua
        sudo mv stylua /usr/local/bin/
        stylua --version
    
    - name: Check Lua code formatting
      run: |
        echo "Checking Lua code formatting with StyLua..."
        
        # First, check if any files need formatting
        if ! stylua --check *.lua; then
          echo "❌ Code formatting issues detected!"
          echo ""
          echo "The following files need formatting. Please run 'stylua *.lua' to fix:"
          echo ""
          # Show the diff for better visibility
          stylua --check *.lua || true
          echo ""
          echo "To fix formatting issues:"
          echo "1. Run: stylua *.lua"
          echo "2. Commit the formatting changes"
          echo "3. Push the updated code"
          exit 1
        else
          echo "✅ All Lua files are properly formatted"
        fi
    
    - name: Validate Lua syntax
      run: |
        echo "Checking Lua syntax for all .lua files..."
        syntax_errors=0
        
        for lua_file in *.lua; do
          if [ -f "$lua_file" ]; then
            echo -n "Checking $lua_file... "
            if luac -p "$lua_file" 2>/dev/null; then
              echo "✅ Valid"
            else
              echo "❌ Syntax Error"
              echo "Detailed error for $lua_file:"
              luac -p "$lua_file"
              syntax_errors=$((syntax_errors + 1))
            fi
          fi
        done
        
        if [ $syntax_errors -gt 0 ]; then
          echo "Error: Found $syntax_errors Lua files with syntax errors!"
          exit 1
        fi
        
        echo "All Lua files have valid syntax ✅"
    
    - name: Validate TOC file
      run: |
        if [ ! -f "SpectrumLootTool.toc" ]; then
          echo "Error: SpectrumLootTool.toc file not found!"
          exit 1
        fi
        
        # Extract version from TOC file and remove all whitespace/newlines
        TOC_VERSION=$(grep "^## Version:" SpectrumLootTool.toc | sed 's/## Version: //' | tr -d '\n\r\t ' | sed 's/[[:space:]]*$//')
        echo "TOC Version: $TOC_VERSION"
        
        # Extract version from Core.lua and remove all whitespace/newlines
        CORE_VERSION=$(grep 'SLH.version = ' Core.lua | sed 's/.*SLH.version = "\(.*\)".*/\1/' | tr -d '\n\r\t ' | sed 's/[[:space:]]*$//')
        echo "Core.lua Version: $CORE_VERSION"
        
        # Debug output with quotes to show any invisible characters
        echo "TOC_VERSION='$TOC_VERSION'"
        echo "CORE_VERSION='$CORE_VERSION'"
        
        # Check if versions match
        if [ "$TOC_VERSION" != "$CORE_VERSION" ]; then
          echo "Error: Version mismatch between TOC ($TOC_VERSION) and Core.lua ($CORE_VERSION)"
          exit 1
        fi
        
        echo "Version validation passed: $TOC_VERSION"
    
    - name: Validate Lua files
      run: |
        # Check that all Lua files mentioned in TOC exist
        grep "\.lua" SpectrumLootTool.toc | tr -d '\r' | while read -r lua_file; do
          if [ ! -f "$lua_file" ]; then
            echo "Error: Lua file $lua_file referenced in TOC but not found!"
            exit 1
          fi
        done
        
        # Check syntax of all Lua files mentioned in TOC
        echo "Validating syntax of TOC-referenced Lua files..."
        grep "\.lua" SpectrumLootTool.toc | tr -d '\r' | while read -r lua_file; do
          echo -n "Checking TOC file $lua_file... "
          if luac -p "$lua_file" 2>/dev/null; then
            echo "✅ Valid"
          else
            echo "❌ Syntax Error"
            echo "Detailed error for $lua_file:"
            luac -p "$lua_file"
            exit 1
          fi
        done
        
        echo "All TOC-referenced Lua files validation passed"
    
    - name: Check addon structure
      run: |
        # Verify required files exist
        required_files=("SpectrumLootTool.toc" "Core.lua" "UI.lua" "Log.lua" "Debug.lua" "README.md")
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Error: Required file $file not found!"
            exit 1
          fi
        done
        
        echo "Addon structure validation passed"
